/****** Object:  Database [DatabaseFirstApproach]    Script Date: 11/30/2016 8:44:20 AM ******/
CREATE DATABASE [DatabaseFirstApproach] ON  PRIMARY 
( NAME = N'DatabaseFirstApproach', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\DatabaseFirstApproach.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DatabaseFirstApproach_log', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\DatabaseFirstApproach_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DatabaseFirstApproach] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DatabaseFirstApproach].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DatabaseFirstApproach] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DatabaseFirstApproach] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DatabaseFirstApproach] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DatabaseFirstApproach] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DatabaseFirstApproach] SET ARITHABORT OFF 
GO

ALTER DATABASE [DatabaseFirstApproach] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DatabaseFirstApproach] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DatabaseFirstApproach] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DatabaseFirstApproach] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DatabaseFirstApproach] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DatabaseFirstApproach] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DatabaseFirstApproach] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DatabaseFirstApproach] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DatabaseFirstApproach] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DatabaseFirstApproach] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DatabaseFirstApproach] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DatabaseFirstApproach] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DatabaseFirstApproach] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DatabaseFirstApproach] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DatabaseFirstApproach] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DatabaseFirstApproach] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DatabaseFirstApproach] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DatabaseFirstApproach] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DatabaseFirstApproach] SET  MULTI_USER 
GO

ALTER DATABASE [DatabaseFirstApproach] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DatabaseFirstApproach] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DatabaseFirstApproach] SET  READ_WRITE 
GO


